server:
  port: 8050
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qipengpai/comic-cloud
          search-paths: config-repo
          username: 1074723451@qq.com
          password: pp210510.
    bus:
      trace:
        enabled: true # 开启cloud bus的跟踪
      refresh:
        enabled: true
      env:
        enabled: true
      enabled: true
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
#          force-pull，配置当本地目录与远程配置有冲突时是否强制拉取配置
#          代码很简单，即为标准的spring-boot项目启动代码
eureka:
  client:
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone:  http://127.0.0.1:1111/eureka,http://127.0.0.1:1112/eureka,http://127.0.0.1:1113/eureka
      #http://130.75.131.241:8761/eureka,http://130.75.131.248:8762/eureka
      #http://134.224.249.33:1111/eureka/  正式库
      #http://134.224.249.33:1111/eureka/  测试库
      #http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#    instance-id: ${spring.application.name}:${docker.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 15 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
    #注册实例文档
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/client/doc.html # ${server.port}为该服务的端口号
#    status-page-url: http://${docker.ipAddress}:${server.port}/client/doc.html # ${server.port}为该服务的端口号

